name: "Terraform EC2"

on:
  workflow_dispatch:
    inputs:
      approve:
        description: 'Approve the Terraform EC2 workflow'
        required: true
  workflow_run:
    workflows: ["Terraform VPC"]
    types:
      - completed

jobs:
  approval:
    runs-on: ubuntu-latest
    steps:
      - name: Approve Terraform EC2 Workflow
        if: github.event_name == 'workflow_dispatch' && github.event.inputs.approve == 'true'
        run: echo "Terraform EC2 workflow approved, proceeding to Terraform steps"

  terraform_ec2:
    name: "Terraform EC2"
    runs-on: ubuntu-latest
    needs: approval
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    defaults:
      run:
        working-directory: EC2

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.1
          terraform_wrapper: false

      - name: Terraform Format
        id: fmt
        run: terraform fmt -check

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color

      - name: Terraform Apply
        run: terraform apply -auto-approve

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
